name: Dev deployment

on:
  push:
    branches: [ dev ]
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: deploy api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USERNAME }}
          key: ${{ secrets.API_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/littlefish-mvp
            git pull origin dev
            git status
            npm install --only=prod
      - name: deploy frontend app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USERNAME }}
          key: ${{ secrets.APP_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/littlefish-mvp
            git pull origin dev
            git status
            cd ./frontend
            npm install --only=prod
            npm build
            rm -rf /var/www/app.littlefish.foundation
            cp  ./build/*  /var/www/app.littlefish.foundation
  
