name: Prod deployment

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: deploy api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USERNAME }}
          password: ${{ secrets.API_PASSWORD }}
          port: 22
          script: |
            which npm
            cd ~/littlefish-mvp
            git pull origin main
            git status
            cd ./api/
            npm install --omit=dev
      - name: deploy frontend app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USERNAME }}
          password: ${{ secrets.APP_PASSWORD }}
          port: 22
          script: |
            cd ~/littlefish-mvp
            git pull origin main
            git status
            cd ./frontend/
            npm install --omit=dev
            export node_options=--max_old_space_size=8192
            npm run build
            rm -rf /var/www/app.littlefish.foundation
            mkdir /var/www/app.littlefish.foundation
            cp  -r ./build/*  /var/www/app.littlefish.foundation