name: Prod deployment

on:
  push:
    branches: [ main ]
jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: deploy api
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_HOST }}
          username: ${{ secrets.API_USERNAME }}
          password: ${{ secrets.API_PASSWORD }}
          port: 22
          script: |
            cd ~/littlefish-mvp
            git pull origin main
            git status
            npm install --only=prod
      - name: deploy frontend app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.APP_HOST }}
          username: ${{ secrets.APP_USERNAME }}
          password: ${{ secrets.APP_PASSWORD }}
          port: 22
          script: |
            cd ~/littlefish-mvp
            git pull origin main
            git status
            cd ./frontend
            npm install --only=prod
            npm build
            rm -rf /var/www/app.littlefish.foundation
            mkdir /var/www/app.littlefish.foundation
            cp  -r ./build/*  /var/www/app.littlefish.foundation